#!/usr/bin/env python3
"""End-to-end driver. Every published output is regenerated by this script.

    python3 run_pipeline.py acquire     archive NIH ExPORTER source files
    python3 run_pipeline.py build       load, validate, annotate
    python3 run_pipeline.py rank        produce ranked tables
    python3 run_pipeline.py affiliation build investigator identity and affiliation spells
    python3 run_pipeline.py harvest     collect PubMed affiliation evidence (slow, cached)
    python3 run_pipeline.py surgery     publication-derived department + NIH agreement
    python3 run_pipeline.py biblio      flagship-journal output and citation impact
    python3 run_pipeline.py mgb         MGH/BWH surgical attribution and context tables
    python3 run_pipeline.py figures     produce figures
    python3 run_pipeline.py validate    reconciliation and QC checks
    python3 run_pipeline.py all         everything, in order
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / "src"))

import pandas as pd

from rankmgb import acquire, annotate, load, rank
from rankmgb.paths import PROCESSED, WORKFLOW_MANIFEST
from rankmgb.util import environment_stamp, get_logger, load_config, read_json, utcnow, write_json

log = get_logger("driver")


def _load_processed() -> tuple[pd.DataFrame, pd.DataFrame]:
    a = PROCESSED / "award_years_annotated.parquet"
    p = PROCESSED / "pi_links.parquet"
    if not a.exists() or not p.exists():
        raise SystemExit("processed tables missing; run `python3 run_pipeline.py build` first")
    return pd.read_parquet(a), pd.read_parquet(p)


def main(argv: list[str]) -> int:
    stage = argv[1] if len(argv) > 1 else "all"
    cfg = load_config()
    steps: list[str] = []

    if stage in ("acquire", "all"):
        acquire.acquire_all(cfg)
        steps.append("acquire")

    if stage in ("build", "all"):
        raw, pis = load.build(cfg)
        ref = annotate.load_reference(cfg)
        annotate.annotate(raw, cfg, ref)
        steps.append("build")

    if stage in ("rank", "all"):
        df, pis = _load_processed()
        ref = annotate.load_reference(cfg)
        rank.build_rankings(df, pis, cfg, ref)
        steps.append("rank")

    if stage in ("affiliation", "all"):
        from rankmgb import affiliation

        df, pis = _load_processed()
        affiliation.run(df, pis)
        steps.append("affiliation")

    if stage in ("surgery", "all"):
        # Publication-derived department for every institution in the registry,
        # with NIH ORG_DEPT kept as an independent comparator.
        from rankmgb import agreement, surgery_ranking, surgical_attribution

        df, pis = _load_processed()
        pub_path = PROCESSED / "pubmed_author_affiliations.parquet"
        if not pub_path.exists():
            raise SystemExit("run `python3 run_pipeline.py harvest` before the surgery stage")
        pub = pd.read_parquet(pub_path)
        attribution = surgical_attribution.attribute(df, pis, pub)
        surgical_attribution.summarise(attribution, cfg)
        agreement.run(attribution)
        surgery_ranking.build_all(cfg)
        steps.append("surgery")

    if stage in ("mgb", "all"):
        # Requires the PubMed harvest, which is slow and cached under
        # data/interim. Run `python3 run_pipeline.py harvest` first.
        from rankmgb import mgb_context, mgb_surgery

        df, pis = _load_processed()
        pub_path = PROCESSED / "pubmed_author_affiliations.parquet"
        if not pub_path.exists():
            raise SystemExit("run `python3 run_pipeline.py harvest` before the mgb stage")
        pub = pd.read_parquet(pub_path)
        res = mgb_surgery.attribute(df, pis, pub)
        mgb_surgery.summarise(res["attribution"], cfg)
        mgb_context.build_all(cfg)
        steps.append("mgb")

    if stage == "harvest":
        from rankmgb import pubmed_evidence

        pubmed_evidence.run(2020, 2026)
        steps.append("harvest")

    if stage in ("biblio", "all"):
        # A second measure of a department: flagship-journal output and citation
        # impact, from the same PubMed harvest plus NIH's iCite service.
        from rankmgb import bibliometrics

        if not (PROCESSED / "pubmed_author_affiliations.parquet").exists():
            raise SystemExit("run `python3 run_pipeline.py harvest` before the biblio stage")
        bibliometrics.build(cfg)
        steps.append("biblio")

    if stage in ("figures", "all"):
        from rankmgb import figures

        figures.build_all(cfg)
        steps.append("figures")

    if stage in ("validate", "all"):
        from rankmgb import validate

        validate.run(cfg)
        validate.sensitivity(cfg)
        steps.append("validate")

    write_json(
        WORKFLOW_MANIFEST,
        {
            "pipeline_version": cfg["pipeline_version"],
            "run_at": utcnow(),
            "stages_run": steps,
            "config": cfg,
            "environment": environment_stamp(),
            "source_manifest": read_json(Path("data/raw/manifest.json")),
        },
    )
    log.info("done: %s", ", ".join(steps))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
